# Changes here will be overwritten by Copier
_commit: v7.3.0-22-g87d8a9b
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-splitfile
project_description: Split a file into parts with a specified size
project_slug: splitfile
project_type: plugin
pypi: true

